DROP TABLE IF EXISTS staging_load;
create table staging_load(
address varchar,
borough varchar,
city varchar,
incident_id varchar,
incident_status varchar,
vehicle_license_plate varchar,
method_of_entry varchar,
occurrence_datetime varchar,
recovery_date varchar,
recovery_status varchar,
report_datetime varchar,
report_number varchar,
state varchar,
vehicle_color varchar,
vehicle_id varchar,
vehicle_year varchar,
vehicle_identification_number varchar,
zip_code varchar,
source_file_name varchar,
data_source varchar,
load_timestamp varchar,
report_date varchar
);

drop table if exists staging_theft;
create table staging_theft(
  incident_id varchar,
  occurrence_datetime varchar,
  report_datetime varchar,
  report_number varchar,
  method_of_entry varchar,
  recovery_date varchar,
  recovery_status varchar,
  data_source varchar,
  source_file_name varchar
);

drop table if exists dim_theft;
create table dim_theft(
  report_id int GENERATED BY DEFAULT AS IDENTITY (1,1),
  effective_start_date timestamp DEFAULT getdate(),
  effective_end_date timestamp DEFAULT NULL,
  is_current char(1) DEFAULT 'Y',
  is_deleted char(1) DEFAULT 'N',
  incident_id varchar,
  occurrence_datetime varchar,
  report_datetime varchar,
  report_number varchar,
  method_of_entry varchar,
  recovery_date varchar,
  recovery_status varchar,
  data_source varchar,
  source_file_name varchar
);


DROP TABLE IF EXISTS staging_location;
CREATE TABLE staging_location(
address_line varchar,
borough varchar,
city varchar,
zip_code varchar,
latitude varchar,
longitude varchar
);

DROP TABLE IF EXISTS dim_location;
CREATE TABLE dim_location(
location_id int generated by default as identity(1,1),
address_line varchar,
borough varchar,
city varchar,
zip_code varchar,
latitude varchar,
longitude varchar
);


DROP TABLE  IF EXISTS staging_vehicle;
CREATE TABLE  staging_vehicle(
vehicle_year varchar,
vehicle_color varchar,
vehicle_identification_number varchar,
vehicle_license_plate varchar
);

DROP TABLE  IF EXISTS dim_vehicle;
CREATE TABLE dim_vehicle(
vehicle_id int generated always as identity(1,1),
vehicle_year varchar,
vehicle_color varchar,
vehicle_identification_number varchar,
vehicle_license_plate varchar
);

DROP TABLE  IF EXISTS fact_motor_theft_vehicle;
CREATE TABLE fact_motor_theft_vehicle(
theft_ref_id int generated always as identity(1,1),
vehicle_id varchar,
make_id varchar,
location_id varchar,
report_id varchar,
report_date varchar,
load_timestamp varchar
);
